"""add_jobs_table

Revision ID: 1eff148a4f82
Revises: 244d16d70b6c
Create Date: 2026-02-25 18:55:30.639823

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector  # noqa: F401 — needed for VECTOR column type
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1eff148a4f82"
down_revision: Union[str, None] = "244d16d70b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("hash", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("canton", sa.String(length=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_snippet", sa.String(length=500), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("salary_min_chf", sa.Integer(), nullable=True),
        sa.Column("salary_max_chf", sa.Integer(), nullable=True),
        sa.Column("salary_original", sa.String(length=200), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "salary_period",
            postgresql.ENUM("yearly", "monthly", "hourly", name="salaryperiod"),
            nullable=True,
        ),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column(
            "seniority",
            postgresql.ENUM(
                "intern",
                "junior",
                "mid",
                "senior",
                "lead",
                "head",
                "director",
                name="seniority",
            ),
            nullable=True,
        ),
        sa.Column(
            "contract_type",
            postgresql.ENUM(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "apprenticeship",
                "temporary",
                name="contracttype",
            ),
            nullable=True,
        ),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("logo", sa.String(length=2048), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("url_last_check", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_index(op.f("ix_jobs_canton"), "jobs", ["canton"], unique=False)
    op.create_index(op.f("ix_jobs_company"), "jobs", ["company"], unique=False)
    op.create_index(op.f("ix_jobs_is_active"), "jobs", ["is_active"], unique=False)
    op.create_index(op.f("ix_jobs_source"), "jobs", ["source"], unique=False)
    op.create_index(op.f("ix_jobs_url"), "jobs", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_url"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_is_active"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_company"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_canton"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
