"""add source_compliance table

Revision ID: 244d16d70b6c
Revises: 53b72b1613ce
Create Date: 2026-02-25 10:00:19.144207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244d16d70b6c'
down_revision: Union[str, None] = '53b72b1613ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_compliance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('robots_txt_ok', sa.Boolean(), nullable=False),
    sa.Column('tos_reviewed_at', sa.Date(), nullable=True),
    sa.Column('tos_notes', sa.String(length=1000), nullable=True),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('last_blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_disable_on_block', sa.Boolean(), nullable=False),
    sa.Column('consecutive_blocks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_compliance_source_key'), 'source_compliance', ['source_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_compliance_source_key'), table_name='source_compliance')
    op.drop_table('source_compliance')
    # ### end Alembic commands ###
