"""add fuzzy_hash and duplicate_of to jobs

Revision ID: b6b766fb5c35
Revises: 1eff148a4f82
Create Date: 2026-02-25 20:17:47.454143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6b766fb5c35"
down_revision: Union[str, None] = "1eff148a4f82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("fuzzy_hash", sa.String(length=32), nullable=True))
    op.add_column(
        "jobs", sa.Column("duplicate_of", sa.String(length=32), nullable=True)
    )
    op.create_index(op.f("ix_jobs_fuzzy_hash"), "jobs", ["fuzzy_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_fuzzy_hash"), table_name="jobs")
    op.drop_column("jobs", "duplicate_of")
    op.drop_column("jobs", "fuzzy_hash")
    # ### end Alembic commands ###
